name: Push image to registry
run-name: ${{ gitea.actor }} pushing to registry 🚀
on: [push]

jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: gitea.9900677.xyz
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=latest
          IMAGE_URI=gitea.9900677.xyz/${{ gitea.repository }}:$IMAGE_TAG
          docker build -t $IMAGE_URI . && docker push $IMAGE_URI